INSERT INTO CARGO (ID,CARGO_TYPE,NAME,WEIGHT) VALUES (
'1_a','FOOD','APPLE',100);
INSERT INTO CARGO (ID,CARGO_TYPE,NAME,WEIGHT) VALUES (
'2_a','CLOTHES','JEANS',200);
INSERT INTO CARGO (ID,CARGO_TYPE,NAME,WEIGHT) VALUES (
'3_a','FOOD','ORANGE',300);


INSERT INTO PUBLIC.CLOTHES_CARGO (CARGO_ID,"SIZE",MATERIAL) VALUES (
'2_a','XXL','COTTON');


INSERT INTO PUBLIC.FOOD_CARGO (CARGO_ID,EXPIRATION_DATE,STORE_TEMPERATURE) VALUES (
'1_a','2025-12-20',-50);
INSERT INTO PUBLIC.FOOD_CARGO (CARGO_ID,EXPIRATION_DATE,STORE_TEMPERATURE) VALUES (
'3_a','2020-11-11',-20);


INSERT INTO PUBLIC.CARRIER (ID,NAME,ADDRESS,CARRIER_TYPE) VALUES (
'1_b','YOUR_DELIVERY','Spb, Nevskiy 800','SHIP');
INSERT INTO PUBLIC.CARRIER (ID,NAME,ADDRESS,CARRIER_TYPE) VALUES (
'2_b','FASTEST EVER','Sp, Prosveheniya 900','PLANE');


INSERT INTO PUBLIC.TRANSPORTATION (CARGO_REF,CARRIER_REF,BILL_TO,TRANSPORTATION_BEGIN_DATE,DESCRIPTION) VALUES (
'1_a','1_b','Ivanov','2010-11-11','Vip order');
INSERT INTO PUBLIC.TRANSPORTATION (CARGO_REF,CARRIER_REF,BILL_TO,TRANSPORTATION_BEGIN_DATE,DESCRIPTION) VALUES (
'2_a','1_b','Petrov','2011-11-11','Fragile');
INSERT INTO PUBLIC.TRANSPORTATION (CARGO_REF,CARRIER_REF,BILL_TO,TRANSPORTATION_BEGIN_DATE,DESCRIPTION) VALUES (
'3_a','2_b','Sidorov','2017-01-01','Fragile');


