
CREATE TABLE PUBLIC.CARGO (
	ID VARCHAR(100) NOT NULL,
	CARGO_TYPE VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	WEIGHT INTEGER NOT NULL,
	CONSTRAINT CARGO_PKEY PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.CLOTHES_CARGO (
	CARGO_ID VARCHAR(100) NOT NULL,
	"SIZE" VARCHAR(100) NOT NULL,
	MATERIAL VARCHAR(100) NOT NULL,
	CONSTRAINT CLOTHES_CARGO_FKEY FOREIGN KEY (CARGO_ID) REFERENCES PUBLIC.CARGO(ID) 
);

CREATE TABLE PUBLIC.FOOD_CARGO (
	CARGO_ID VARCHAR(100) NOT NULL,
	EXPIRATION_DATE DATE NOT NULL,
	STORE_TEMPERATURE INTEGER NOT NULL,
	CONSTRAINT FOOD_CARGO_FKEY FOREIGN KEY (CARGO_ID) REFERENCES PUBLIC.CARGO(ID)

CREATE TABLE PUBLIC.CARRIER (
	ID VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	ADDRESS VARCHAR(100) NOT NULL,
	CARRIER_TYPE VARCHAR(100) NOT NULL,
	CONSTRAINT CARRIER_PKEY PRIMARY KEY (ID)
);


CREATE TABLE PUBLIC.TRANSPORTATION (
	CARGO_REF VARCHAR(100) NOT NULL,
	CARRIER_REF VARCHAR(100) NOT NULL,
	BILL_TO VARCHAR(100) NOT NULL,
	TRANSPORTATION_BEGIN_DATE VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
	CONSTRAINT TRANSPORTATION_CARGO_FKEY FOREIGN KEY (CARGO_REF) REFERENCES PUBLIC.CARGO(ID),
	CONSTRAINT TRANSPORTATION_CARRIER_FKEY FOREIGN KEY (CARRIER_REF) REFERENCES PUBLIC.CARRIER(ID) 
);
